//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace La_tiendita.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DetalleVenta
    {
        [Display(Name = "Id Detalle")]
        public int Id_detalle { get; set; }

        [Display(Name = "Venta")]
        public Nullable<int> Id_venta { get; set; }

        [Display(Name = "Producto")]
        public Nullable<int> Id_producto { get; set; }

        [Display(Name = "Cantidad")]
        public Nullable<int> Cantidad { get; set; }

        [Display(Name = "Subtotal")]
        public Nullable<decimal> Subtotal { get; set; }

        [Display(Name = "Producto")]
        public virtual Producto Producto { get; set; }

        [Display(Name = "Ventas")]
        public virtual Ventas Ventas { get; set; }
    }
}
