//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace La_tiendita.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.DetalleVenta = new HashSet<DetalleVenta>();
        }

        [Display(Name = "Id Producto")]
        public int Id_producto { get; set; }

        [Display(Name = "Producto")]
        public string produtco { get; set; }

        [Display(Name = "Descripción")]
        public string descripcion_producto { get; set; }

        [Display(Name = "Fecha de caducidad")]
        public Nullable<System.DateTime> fecha_caducidad { get; set; }

        [Display(Name = "Existencias")]
        public Nullable<int> existencia_de_producto { get; set; }

        [Display(Name = "Precio de compra")]
        public Nullable<decimal> precio_compra { get; set; }

        [Display(Name = "Precio de venta")]
        public Nullable<decimal> precio_venta { get; set; }

        [Display(Name = "Categoria")]
        public Nullable<int> Id_categoria { get; set; }

        [Display(Name = "Categoria")]
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
    }
}
