//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace La_tiendita.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vendedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendedor()
        {
            this.Ventas = new HashSet<Ventas>();
        }

        [Display(Name = "Id Vendedor")]
        public int Id_vendedor { get; set; }

        [Display(Name = "Nombre del vendedor")]
        public string Nombre_vendedor { get; set; }

        [Display(Name = "Corro del vendedor")]
        public string Correo_vendedor { get; set; }

        [Display(Name = "Telefono del vendedor")]
        public string Telefono_vendedor { get; set; }

        [Display(Name = "DUI del vendedor")]
        public string Dui_vendedor { get; set; }

        [Display(Name = "Usuario del vendedor")]
        public string Usuario_vendedor { get; set; }

        [Display(Name = "Contraseña")]
        public string contasena { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}
